name: Update Recent Repos

on:
  schedule:
    - cron: '0 0 * * *' # Executar diariamente

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
    - name: Use GitHub Script
      uses: actions/github-script@v5
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const response = await github.repos.listForUser({
            username: 'lucaskawatoko',
            per_page: 5,
            sort: 'created',
            direction: 'desc',
          });

          const repos = response.data.map(repo => `- [${repo.name}](${repo.html_url})`).join('\n');

          const readmePath = `${process.env.GITHUB_WORKSPACE}/README.md`;
          let readmeContent = fs.readFileSync(readmePath, 'utf8');

          readmeContent = readmeContent.replace("<!-- REPOS_SECTION_START -->\n<!-- REPOS_SECTION_END -->",
                                                  `<!-- REPOS_SECTION_START -->\n${repos}\n<!-- REPOS_SECTION_END -->`);

          fs.writeFileSync(readmePath, readmeContent);
